spring.application.name=Backend

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/shipmentTrackingPortal
spring.datasource.username=root
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.context-path=/api/v1
jwt.secretKey=ashdahscncgye3784eichuie8q7wyeqexndd9wioeqjmjxsjxnhduiwhwxdjsiddca7eadsdcndihxxeh232y7yexnhsjkh